version: '3'
services:
  bot:
    build: .
    restart: always
    links:
      - redis
  redis:
    restart: always
    image: redis:4.0-alpine
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: ['redis-server', '--appendonly', 'yes']
